# NOTE: This file is not managed by Projen because if you enable Dependabot through Projen,
# it will delete the upgrade-main job and expect you to only use Dependabot for updates.
# That is not what we want either; we just want to use Dependabot for security updates.

version: 2
updates:
  - package-ecosystem: npm
    versioning-strategy: lockfile-only
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: projen
    labels:
      - auto-approve
      - automerge
      - dependencies
      - security
    # Disable version updates for npm dependencies, only use Dependabot for security updates
    open-pull-requests-limit: 0
  # Have Dependabot manage version upgrades for the integration tests (test-stacks directory)
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    directory: "/test-stacks"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
      # For providers, ignore all patch updates for version updates only
      - dependency-name: "@cdktf/provider-*"
        update-types: ["version-update:semver-patch"]
    groups:
      cdktf:
        patterns:
          - "cdktf"
          - "cdktf-cli"
          - "@cdktf/*"
      jest:
        patterns:
          - "jest"
          - "ts-jest"
          - "@types/jest"
          - "@jest/*"
